// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview A flow that generates an Instagram caption for a given image and creative Indian name.
 *
 * - generateInstagramCaption - A function that generates an Instagram caption.
 * - GenerateInstagramCaptionInput - The input type for the generateInstagramCaption function.
 * - GenerateInstagramCaptionOutput - The return type for the generateInstagramCaption function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateInstagramCaptionInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo to generate a caption for, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  creativeIndianName: z.string().describe('A creative Indian name related to the image.'),
});
export type GenerateInstagramCaptionInput = z.infer<
  typeof GenerateInstagramCaptionInputSchema
>;

const GenerateInstagramCaptionOutputSchema = z.object({
  instagramCaption: z.string().describe('The generated Instagram caption.'),
});
export type GenerateInstagramCaptionOutput = z.infer<
  typeof GenerateInstagramCaptionOutputSchema
>;

export async function generateInstagramCaption(
  input: GenerateInstagramCaptionInput
): Promise<GenerateInstagramCaptionOutput> {
  return generateInstagramCaptionFlow(input);
}

const generateInstagramCaptionPrompt = ai.definePrompt({
  name: 'generateInstagramCaptionPrompt',
  input: {schema: GenerateInstagramCaptionInputSchema},
  output: {schema: GenerateInstagramCaptionOutputSchema},
  prompt: `You are an Instagram influencer specializing in creating engaging content.

  Given an image and a creative Indian name, generate a relevant and engaging Instagram caption.

  Image: {{media url=photoDataUri}}
  Creative Indian Name: {{{creativeIndianName}}}

  Caption:`,
});

const generateInstagramCaptionFlow = ai.defineFlow(
  {
    name: 'generateInstagramCaptionFlow',
    inputSchema: GenerateInstagramCaptionInputSchema,
    outputSchema: GenerateInstagramCaptionOutputSchema,
  },
  async input => {
    const {output} = await generateInstagramCaptionPrompt(input);
    return output!;
  }
);
